"""about me optional

Revision ID: 1f6b8843ef09
Revises: e4fc533c05b6
Create Date: 2025-02-14 14:37:28.207190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f6b8843ef09'
down_revision = 'e4fc533c05b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=mysql.VARCHAR(length=140),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('about_me',
               existing_type=mysql.VARCHAR(length=140),
               nullable=False)

    # ### end Alembic commands ###
